- project:
    check: &jobs
      jobs:
        - sf-rpm-build
        - pnpm-test:
            required-projects:
              - software-factory/re-gerrit
    gate: *jobs
    release:
      jobs:
        - sf-rpm-publish
